name: publisher-subscriber
base: core20
version: '0.1'
summary: ROS Example
description: |
  The ROS publisher/subscriber example packaged as a snap.

grade: stable
confinement: strict

parts:
  workspace:
    plugin: catkin
    source: .
    catkin-packages: [beginner_tutorials]
    stage-packages:
       - ros-noetic-rosbash # for rosrun
       - ros-noetic-roslaunch # for roscore

apps:
  roscore:
    command: opt/ros/noetic/bin/roscore
    plugs: [network, network-bind]
    extensions: [ros1-noetic]

  talker:
    # Use talker.py if you followed the Python tutorial
    command: opt/ros/noetic/bin/rosrun beginner_tutorials talker.py
    plugs:
       - network
       - network-bind
    extensions: [ros1-noetic]
    environment:
      "ROS_HOME": "$SNAP_USER_DATA" # remap ROS_HOME for rospack temporary cache file

  listener:
    # Use listener.py if you followed the Python tutorial
    command: opt/ros/noetic/bin/rosrun beginner_tutorials listener.py
    plugs:
       - network
       - network-bind
    extensions: [ros1-noetic]
    environment:
      "ROS_HOME": "$SNAP_USER_DATA" # remap ROS_HOME for rospack temporary cache file
